-- *********
-- SubQuery
-- *********

-- #7101
SELECT * FROM T_EMP ;

SELECT ENAME , SAL 
FROM T_EMP 
WHERE SAL > (SELECT SAL 
FROM T_EMP 
WHERE ENAME = 'SCOTT');

SELECT SAL 
FROM T_EMP 
WHERE ENAME = 'SCOTT';

-- #7102
SELECT MAX(HEIGHT)
FROM T_STUDENT ;

SELECT NAME , HEIGHT 
FROM T_STUDENT 
WHERE HEIGHT = (SELECT MAX(HEIGHT) FROM T_STUDENT);

-- 1. 단일행 SubQuery
-- = , !=, <> , >, >= , <, <=
-- 결과가 한개 1행만 나오는 것.
-- 단일행 Sub Query 의  WHERE 에서 사용되는 연산자

-- #7103
SELECT DEPTNO1 FROM T_STUDENT WHERE name = '이윤나';

SELECT s.NAME "이름", d.DNAME "1전공"
FROM T_STUDENT s, T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO AND s.DEPTNO1 = (SELECT DEPTNO1 FROM T_STUDENT WHERE name = '이윤나');

-- #7104
SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '송도권';

SELECT p.NAME "교수명", TO_CHAR( p.HIREDATE, 'YYYY-MM-DD') "입사일", d.DNAME "학과명"
FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE p.DEPTNO = d.DEPTNO AND p.HIREDATE > (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '송도권');


-- #7105
SELECT AVG(WEIGHT) FROM T_STUDENT WHERE DEPTNO1 = 101;

SELECT NAME "이름", WEIGHT "몸무게"
FROM T_STUDENT 
WHERE WEIGHT > (SELECT AVG(WEIGHT) FROM T_STUDENT WHERE DEPTNO1 = 101);

-- #7106
SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '심슨';
SELECT PAY FROM T_PROFESSOR WHERE NAME = '조인형';

SELECT NAME "이름", PAY "급여", TO_CHAR(HIREDATE , 'YYYY-MM-DD') "입사일" 
FROM T_PROFESSOR 
WHERE HIREDATE = (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '심슨') 
AND PAY < (SELECT PAY FROM T_PROFESSOR WHERE NAME = '조인형');