-- ************
-- 다중행 SubQuery
-- ************

-- #7107
SELECT * FROM T_EMP2 ;
SELECT * FROM T_DEPT2 ;

SELECT DCODE FROM T_DEPT2 WHERE AREA = '서울지사';

SELECT EMPNO , NAME , DEPTNO 
FROM T_EMP2 
WHERE DEPTNO IN (SELECT DCODE FROM T_DEPT2 WHERE AREA = '서울지사');

-- #7108
SELECT PAY FROM T_EMP2 WHERE POST = '과장';

SELECT NAME "이름", POST "직급", TO_CHAR(PAY , '999,999,999') || '원' "연봉" 
FROM T_EMP2 
WHERE PAY >ANY (SELECT PAY FROM T_EMP2 WHERE POST = '과장');

-- #7109
SELECT WEIGHT FROM T_STUDENT WHERE GRADE = 4;

SELECT name "이름", GRADE "학년", WEIGHT "몸무게"
FROM T_STUDENT 
WHERE WEIGHT <ALL (SELECT WEIGHT FROM T_STUDENT WHERE GRADE = 4);

