-- *********************
-- Multi-COLUMN SubQuery
-- *********************

-- #7201
SELECT GRADE , MAX(HEIGHT ) 
FROM T_STUDENT 
GROUP BY GRADE ;

-- max(height)의 학생 이름이 모니~
SELECT GRADE "학년", NAME "이름", HEIGHT "키"
FROM T_STUDENT 
WHERE (GRADE , HEIGHT ) IN (SELECT GRADE , MAX(HEIGHT ) FROM T_STUDENT GROUP BY GRADE )
ORDER BY "학년" ASC ;

-- #7202
SELECT * FROM T_PROFESSOR ;
SELECT * FROM T_DEPARTMENT ;
SELECT DEPTNO , MIN(HIREDATE ) FROM T_PROFESSOR GROUP BY DEPTNO ;

SELECT p.PROFNO "교수번호", p.NAME "교수명", TO_CHAR(p.HIREDATE , 'YYYY-MM-DD') "입사일", d.DNAME "학과명"
FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE p.DEPTNO = d.DEPTNO AND (p.DEPTNO , p.HIREDATE ) IN (SELECT DEPTNO , MIN(HIREDATE ) FROM T_PROFESSOR GROUP BY DEPTNO )
ORDER BY "학과명" ASC;

-- #7203
SELECT POST , MAX(PAY ) FROM T_EMP2 GROUP BY POST ;

SELECT NAME "사원명", POST "직급", PAY "연봉"
FROM T_EMP2 
WHERE (POST , PAY ) IN (SELECT POST , MAX(PAY ) FROM T_EMP2 GROUP BY POST);

--#7204
SELECT * FROM T_EMP2 ;
SELECT * FROM T_DEPT2 ;

SELECT AVG(PAY ) FROM T_EMP2 GROUP BY DEPTNO ;
SELECT d.DNAME "부서명", e.NAME "직원명", e.PAY "연봉"
FROM T_EMP2 e, T_DEPT2 d
WHERE e.DEPTNO = d.DCODE 
AND e.PAY <ALL (SELECT AVG(PAY ) FROM T_EMP2 GROUP BY DEPTNO )
ORDER BY e.PAY ASC ;

-- *********************
-- Correlated SubQuery
-- *********************

-- #7205
SELECT a.NAME "사원이름", nvl(a.POST, ' ') "직급", a.PAY "급여"
FROM T_EMP2  a 
WHERE a.PAY >= (SELECT AVG(b.PAY )FROM T_EMP2 b WHERE nvl(a.POST, ' ')  = nvl(b.POST, ' '));

SELECT AVG(b.PAY )FROM T_EMP2 b WHERE '과장' = b.POST;

-- #7206
SELECT 
NAME "사원이름", 
(SELECT DNAME FROM T_DEPT2 d WHERE e.DEPTNO = d.DCODE ) "부서이름"
FROM T_EMP2 e;













