-- 계층형 쿼리 (Hierarchical Query)

SELECT * FROM T_DEPT2 ; -- 서로의 계층 관게를 주목해야 한다.

SELECT LPAD(DNAME , 10 , '*') FROM T_DEPT2;

-- LEVEL 
SELECT DNAME , LEVEL 
FROM T_DEPT2 
CONNECT BY PRIOR DCODE = PDEPT 
START WITH DCODE = 0001
;


SELECT DNAME , LEVEL 
FROM T_DEPT2 
CONNECT BY PRIOR PDEPT = DCODE 
START WITH DCODE = 0001
;


-- PIOR 를 다른데 주면?
SELECT DNAME , LEVEL 
FROM T_DEPT2 
CONNECT BY DCODE = PRIOR PDEPT 
START WITH DCODE = 0001
;


SELECT DCODE , DNAME , PDEPT , LEVEL 
FROM T_DEPT2 
CONNECT BY DCODE = PRIOR PDEPT 
-- START WITH DCODE = 1005 -- S/W 지원(1)-> 기술부(2) -> 사장실(3)
START WITH DCODE = 1011
;

SELECT LPAD(DNAME , LEVEL * 6, '*') 부서명 
FROM T_DEPT2
CONNECT BY PRIOR DCODE = PDEPT 
START WITH DCODE = 0001;


-------
SELECT * FROM T_EMP2 ;

SELECT LPAD(e.NAME || ' ' || d.dname || ' ' || NVL(e.POST, '사원'), LEVEL * 15, '-') "이름과 직급"
FROM T_EMP2 e , (SELECT dname, dcode, pdept FROM T_DEPT2 ) d
WHERE e.DEPTNO = d.dcode
CONNECT BY PRIOR e.EMPNO = e.PEMPNO 
START WITH e.EMPNO = 20000101
;

SELECT LEVEL - 1 HR
FROM DUAL 
CONNECT BY LEVEL < 24;

















